### PR TITLE
fix Array[String] for SequenceExample

### PR DESCRIPTION
**Pull request by doldre**
ArrayType(String) should be a Feature not a FeatureList.

If row element is ArrayType(StringType, _),  it will go to https://github.com/tensorflow/ecosystem/blob/master/spark/spark-tensorflow-connector/src/main/scala/org/tensorflow/spark/datasources/tfrecords/serde/DefaultTfRecordRowEncoder.scala#L194, triger a RuntimeException.
```scala
case _ => throw new RuntimeException(s"Cannot convert row element ${row.get(index)} to FeatureList.")
```

### CODE REVIEW

**Comment by doldre** [comment]
@googlebot I signed it!

**Comment by doldre** [comment]
@googlebot I fixed it

**Comment by jhseu** [comment]
Mind adding a test?

**Comment by doldre** [comment]
> Mind adding a test?

Done

**Comment by doldre** [comment]
@jhseu gentle ping : )

**Pull request merged**
