### PR TITLE
BooleanType support

### PR DESCRIPTION
**Pull request by dav009**
Converting a Dataframe with a  `BooleanType` column ends up in exceptions as that type is not in the mapping.
This PR adds `BooleanType` to the mapping. Not sure if it was left intentionally  out, if so it would be good to document it.

Thanks for this project, indeed very useful.

### CODE REVIEW

**Comment by dav009** [comment]
@googlebot I signed it!

**Comment by jhseu** [comment]
@skavulya Mind taking a look?

**Comment by skavulya** [comment]
Will do

**Comment by skavulya** [comment]
@dav009 Thanks for your contribution. It looks good. Please add a BooleanType to the supported types in the README then the PR should be ready for merge.

**Comment by dav009** [comment]
@skavulya done 👍

**Comment by skavulya** [comment]
@dav009 Thanks! 
@jhseu The PR is ready for merge

**Comment by dav009** [comment]
@googlebot I signed it!

**Pull request merged**
